{"version":1,"defects":{"Warning":6,"Tests\\Unit\\RouterTest::it_registers_a_route":4,"Tests\\Unit\\RouterTest::it_registers_a_get_route":4,"Tests\\Unit\\RouterTest::it_throws_route_not_found_exception with data set #0":4,"Tests\\Unit\\RouterTest::it_throws_route_not_found_exception with data set #1":4,"Tests\\Unit\\RouterTest::it_throws_route_not_found_exception with data set #2":4,"Tests\\Unit\\RouterTest::it_throws_route_not_found_exception with data set #3":4,"Tests\\Unit\\RouterTest::it_resolves_route_from_a_closure":4,"Tests\\Unit\\RouterTest::it_resolves_route":4,"Error":4,"Tests\\Unit\\RouterTest::it_resolve_route":4,"tests\\Unit\\Services\\InvoiceServiceTest::it_processes_invoice":3},"times":{"Warning":0.004,"Tests\\Unit\\RouterTest::it_registers_a_route":0.005,"Tests\\Unit\\RouterTest::it_registers_a_get_route":0,"Tests\\Unit\\RouterTest::it_registers_a_post_route":0,"Tests\\Unit\\RouterTest::it_throws_route_not_found_exception with data set #0":0.022,"Tests\\Unit\\RouterTest::it_throws_route_not_found_exception with data set #1":0,"Tests\\Unit\\RouterTest::it_throws_route_not_found_exception with data set #2":0,"Tests\\Unit\\RouterTest::it_throws_route_not_found_exception with data set #3":0,"Tests\\Unit\\RouterTest::it_resolves_route_from_a_closure":0,"Tests\\Unit\\RouterTest::it_resolves_route":0,"Error":0.001,"Tests\\Unit\\RouterTest::it_resolve_route":0,"tests\\Unit\\Services\\InvoiceServiceTest::it_processes_invoice":0.017,"tests\\Unit\\Services\\InvoiceServiceTest::it_sends_receipt_email_when_invoice_is_processed":0.118}}